typography_spectrum: 0.3653246567118913
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.18441688898019493
  lightness: 0.4375
  saturation: 0.6576359269674867
  rhythmicContrast: 0.17714951024390757
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3901507460977882
analytics:
  google: UA-83130120-1
  facebook: null
  twitter: null
author:
  name: Timothy Boye
  email: contact@timothyboye.com
  url: 'http://timothyboye.com'
name: Timothy Boye
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'https://au.linkedin.com/in/timothyboye'
    type: external
  - name: Github
    url: 'https://github.com/timothyBoye'
    type: external
  - name: Contact
    id: 168c20b7-3bab-420c-a69d-609869eb0f75
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Timothy Boye
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f1788e4-b3a3-466d-b897-378b408ba07a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f1788e4-b3a3-466d-b897-378b408ba07a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Technologist
purpose: []
