typography_spectrum: 0.2573356390930712
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12268466805107892
  lightness: 0.8155256235040724
  saturation: 0.05383202410303056
  rhythmicContrast: 0.6391270500607789
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13353103818371892
analytics:
  google: null
  facebook: null
  twitter: null
name: Timothy Boye
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Timothy Boye
description: Technologist and life enthusiast
purpose: []
