layout_spectrum: 0.17770075984299183
typography_spectrum: 0.5278714373707771
color:
  brandColors:
    - '#343434'
    - '#D9D9D9'
    - '#FBFBFB'
    - '#ADADAD'
    - '#7E7E7E'
  brandStrength: 0.45958072831854224
  lightness: 0.45529518369585276
  saturation: 0.036665928084403276
  rhythmicContrast: 0.9538233887869865
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Timothy Boye
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Timothy Boye
description: Technologist and life enthusiast
purpose: []
