name: Timothy Boye
favicon: null
layout_spectrum: 0.4015511793550104
typography_spectrum: 0.17544541391544044
navigation:
  - name: LinkedIn
    url: 'https://au.linkedin.com/in/timothyboye'
    type: external
  - name: Email
    url: 'mailto:contact@timothyboye.com'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Timothy Boye
description: Technologist and life enthusiast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83130120-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.18441688898019493
  lightness: 0.4375
  saturation: 0.6576359269674867
  rhythmicContrast: 0.17714951024390757
purpose: []
